name: Lint

on: [push, pull_request]

jobs:
  lintcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
      - name: Install poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install --with dev
      - name: Run isort
        run: poetry run isort --check-only --diff mash --profile black
      - name: Run mypy
        run: poetry run mypy mash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
